stow:
	stow --target=$$HOME brew
	stow --target=$$HOME git
	stow --target=$$HOME ideavim
	stow --target=$$HOME tmux
	stow --target=$$HOME zsh
	stow --target=$$HOME/.config/ nvim
	stow --target=$$HOME/Library/Application\ Support\/Alfred/ alfred
	stow --target=$$HOME/Library/Application\ Support\/JetBrains/IdeaIC2023.1/ intellij

