stow:
	stow --target=$$HOME asdf 
	stow --target=$$HOME brew
	stow --target=$$HOME git
	stow --target=$$HOME hammerspoon
	stow --target=$$HOME ideavim
	stow --target=$$HOME tmux
	stow --target=$$HOME zsh
	stow --target=$$HOME/.config/ nvim
	stow --target=$$HOME/Library/Application\ Support\/Alfred/ alfred
	stow --target=$$HOME/Library/Application\ Support\/JetBrains/IdeaIC2023.1/ intellij
	stow --target=$$HOME/.config/ yabai
	stow --target=$$HOME/.config/ skhd
	stow --target=$$HOME/.config/ aerospace

