alias dps="docker ps"
alias git-branch-history="git log --graph --decorate --oneline"
alias ls="gls --color=auto"
alias ll="gls -alh --color=auto"
alias py-new-venv="python3 -m venv .venv"
alias py-activate="source .venv/bin/activate"
alias tedit="open -e"
