# custom IntelliJ IDEA properties (expand/override 'bin/idea.properties')


# intellisense.filesize increased to support working with large protobuf source files.
idea.max.intellisense.filesize=20000
